In [1]:
import pandas as pd

In [ ]:
s2 = pd.Series([90, 80, 70], index=["국어", "영어", "수학"])
print(s2)
display(s2)
s2 # display(s2)

국어    90
영어    80
수학    70
dtype: int64

국어    90
영어    80
수학    70
dtype: int64

In [5]:
x = 10
y = 20
x
y

20

In [6]:
x = 10
y = 20
display(x)
display(y)

10

20

In [ ]:
display(s2.loc["영어"])
display(s2.iloc[1]) # Integer Location

np.int64(80)

np.int64(80)

In [11]:
df1 = pd.DataFrame({
    "이름":["홍길동", "김철수", "이영희"],
    "나이":[20, 30, 25],
    "점수":[90, 80, 95]
}, index=["첫번째", "두번째", "세번째"])

# print(df1)
# display(df1)
df1

      이름  나이  점수
첫번째  홍길동  20  90
두번째  김철수  30  80
세번째  이영희  25  95

In [12]:
df1.loc["두번째"]

이름    김철수
나이     30
점수     80
Name: 두번째, dtype: object

In [13]:
df1.iloc[1]

이름    김철수
나이     30
점수     80
Name: 두번째, dtype: object

In [14]:
df2 = pd.DataFrame({
    "나이":[20, 30, 25],
    "점수":[90, 80, 95]
}, index=["홍길동", "김철수", "이영희"])
df2

     나이  점수
홍길동  20  90
김철수  30  80
이영희  25  95

In [15]:
df2.reset_index()
df2

     나이  점수
홍길동  20  90
김철수  30  80
이영희  25  95

In [17]:
df3 = df2.reset_index()
df3

df3.iloc[0]

index    홍길동
나이        20
점수        90
Name: 0, dtype: object

In [18]:
print(type(df1.iloc[0]))

<class 'pandas.Series'>