In [ ]:
# loc[행옵션, 열옵션] : 레이블 인덱스
# iloc[행옵션, 열옵션] : 위치값(Integer Location)
# [] : 열 레이블, 표현식(T/F 조건식, 논리식, 슬라이싱, ...)

In [1]:
import pandas as pd

df = pd.DataFrame({
    '이름': ['김철수', '이영희', '박민수', '최수진', '정우진'],
    '학년': [1, 2, 1, 3, 2],
    '점수': [85, 92, 78, 95, 88]
}, index=['A', 'B', 'C', 'D', 'E'])

print(df)

    이름  학년  점수
A  김철수   1  85
B  이영희   2  92
C  박민수   1  78
D  최수진   3  95
E  정우진   2  88

In [3]:
df.loc['B'] # df.loc['B', :]

이름    이영희
학년      2
점수     92
Name: B, dtype: object

In [4]:
df.loc['B', '점수']

np.int64(92)

In [5]:
df.iloc[0, 2] # index 레이블이 숫자로 되어있다면

np.int64(85)

In [ ]:
df["이름"] # 열이름 -> 지정 열 전체 행 # 식 -> 지정 행 전체 열

A    김철수
B    이영희
C    박민수
D    최수진
E    정우진
Name: 이름, dtype: str

In [7]:
df

    이름  학년  점수
A  김철수   1  85
B  이영희   2  92
C  박민수   1  78
D  최수진   3  95
E  정우진   2  88

In [ ]:
df["A":"A"] # 식 -> 지정 식 행 전체열

    이름  학년  점수
A  김철수   1  85

In [14]:
df[:]

    이름  학년  점수
A  김철수   1  85
B  이영희   2  92
C  박민수   1  78
D  최수진   3  95
E  정우진   2  88

In [ ]:
df[0:1] # 식 -> 지정 식 행 전체열

    이름  학년  점수
A  김철수   1  85

In [10]:
df["이름":"이름"]

Empty DataFrame
Columns: [이름, 학년, 점수]
Index: []

In [13]:
df[["이름", "학년"]]

    이름  학년
A  김철수   1
B  이영희   2
C  박민수   1
D  최수진   3
E  정우진   2

In [15]:
df["A":"E"]

    이름  학년  점수
A  김철수   1  85
B  이영희   2  92
C  박민수   1  78
D  최수진   3  95
E  정우진   2  88

In [ ]:
# [열이름], [열이름리스트] -> 열선택
# [식] -> 행선택
# [:]
# [조건식]

In [17]:
# t = df["점수"]
# df[t > 90]
df[df["점수"] > 90]
# df["점수" > 90] # [값] -> 컬럼이름, 컬럼이름들 리스트값 -> 열출력
# [식] -> 행이 출력

    이름  학년  점수
B  이영희   2  92
D  최수진   3  95

In [ ]:
import seaborn as sns

In [19]:
mpg_df = sns.load_dataset("mpg")
mpg_df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [20]:
# [5, 10, 15, 20] > 10 # [False, False, True, True] -> [15, 20]
[x>10 for x in [5, 10, 15, 20]] # 컴프리핸션

[False, False, True, True]

In [21]:
[x for x in [5, 10, 15, 20] if x>10]

[15, 20]

In [23]:
type(df["점수"])

df["점수"] > 90

A    False
B     True
C    False
D     True
E    False
Name: 점수, dtype: bool

In [ ]:
# 리스트 > 10 -> 문법적 에러 -> 컴프리핸션
# narray > 10
# 시리즈 > 10 -> 문법적 에러 X

In [24]:
# [5, 10, 15, 20] > 10
# [5, 10, 15, 20] -> numpy.narray, pandas.Series 변환하면 > 10
pd.Series([5, 10, 15, 20]) > 10

0    False
1    False
2     True
3     True
dtype: bool