In [1]:
import pandas as pd

In [2]:
# {레이블 : [], 레이블 : []}
df1 = pd.DataFrame({
    "이름":["민수", "지영"],
    "점수":[90, 85]
    })
# print() 터미널 출력
# display() 노트북 셀에 최적화 출력
df1

   이름  점수
0  민수  90
1  지영  85

In [4]:
# index값 행레이블(레이블 인덱스), columns값 열레이블(레이블 인덱스)
# 생략하면 위치값으로 기본값 설정된다.

df2 = pd.DataFrame([
    ["민수", 90], # 1행
    ["지영", 85], # 2행
], index=["첫번째", "두번째"], columns=["이름", "점수"])
df2

     이름  점수
첫번째  민수  90
두번째  지영  85

In [6]:
df3 = pd.DataFrame([
    {"이름":"민수", "점수":90}, # 1행
    {"이름":"지영", "점수":100}, # 2행
])
df3

   이름   점수
0  민수   90
1  지영  100

In [7]:
import numpy as np

# numpy의 2차원 배열 - 모든 데이터 타입이 동일
df3 = pd.DataFrame(np.array([
    [1, 2], 
    [3, 4],
]), columns=["x", "y"])

df3

   x  y
0  1  2
1  3  4

In [8]:
# 이름, 나이, 성별 데이터로 DataFrame 생성
df = pd.DataFrame({
    '이름': ['철수', '영희', '민수', '지영', '준호'],
    '나이': [20, 21, 20, 22, 21],
    '성별': ['남', '여', '남', '여', '남']
})

print(df)

   이름  나이 성별
0  철수  20  남
1  영희  21  여
2  민수  20  남
3  지영  22  여
4  준호  21  남

In [9]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
df.columns

Index(['이름', '나이', '성별'], dtype='str')

In [11]:
df.values # numpy의 array값으로 반환

array([['철수', 20, '남'],
       ['영희', 21, '여'],
       ['민수', 20, '남'],
       ['지영', 22, '여'],
       ['준호', 21, '남']], dtype=object)

In [12]:
df.dtypes # 반환값 Series 타입 index=columns

이름      str
나이    int64
성별      str
dtype: object

In [13]:
print(df.shape, df.size, df.ndim)

(5, 3) 15 2

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      5 non-null      str
 1   나이      5 non-null      int64
 2   성별      5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [ ]:
# 저장 단위
# KB -> MB -> GB -> TB -> PB -> EB -> ZB -> YB -> RB -> QB

In [15]:
df.head(2)

   이름  나이 성별
0  철수  20  남
1  영희  21  여

In [16]:
df.tail(2)

   이름  나이 성별
3  지영  22  여
4  준호  21  남

In [17]:
df.head() # 기본 5

   이름  나이 성별
0  철수  20  남
1  영희  21  여
2  민수  20  남
3  지영  22  여
4  준호  21  남

In [19]:
# [] 인덱싱연산자 매개값 index 사용(열 레이블, 표현식)
df["성별"].unique() # sql select distinct

<StringArray>
['남', '여']
Length: 2, dtype: str

In [20]:
df["성별"].nunique() # 범주값의 종류

2