In [1]:
import pandas as pd

In [2]:
data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "점수": [85, None, 90, 75, None],
    "출석": [True, True, None, True, False]
}

df = pd.DataFrame(data)

print(df) # 데이터프레임은 객체타입은 None, 숫자타입은 NaN으로 처리

print(df.isna())
print(df.isnull())

    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   NaN  False
      이름     점수     출석
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False
      이름     점수     출석
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

In [3]:
df.isna().sum() # 결측치 개수 반환 X DataFrame.isna() 메서드
# 0 0 0
# 0 1 0
# 0 0 1
# 0 0 0
# 0 1 0

이름    0
점수    2
출석    1
dtype: int64

In [4]:
df["점수"].isna() # Series.isna() 메서드

0    False
1     True
2    False
3    False
4     True
Name: 점수, dtype: bool

In [5]:
df

    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   NaN  False

In [6]:
# df[[False, True, False, False, True]]
df[df["점수"].isna()]

    이름  점수     출석
1  이서연 NaN   True
4  정현우 NaN  False

In [7]:
cond = df["점수"].isna()
df[cond]

# df[조건식] df[size가 len(df) 같은 bool 배열]

    이름  점수     출석
1  이서연 NaN   True
4  정현우 NaN  False

In [8]:
# 0 김민준 85.0 True
# 1 이서연 NaN True
# 2 박지훈 90.0 None
# 3 최유진 75.0 True
# 4 정현우 Nan False

df[df["이름"] != "김민준"]

    이름    점수     출석
1  이서연   NaN   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   NaN  False

In [9]:
df["이름"] != "김민준"

0    False
1     True
2     True
3     True
4     True
Name: 이름, dtype: bool

In [10]:
cond = df["점수"].isna() # [False, True, False, False, True] 시리즈 반환
print(df[cond]) # df[[False, True, False, False, True]] => True인 인덱스1, 4행 출력

# 한줄의 코드로 만들면
print(df[df["점수"].isna()]) # df[조건] -> 행반환

# cond가 True 이름만 출력 => loc[] 인덱스 사용
# []연산자 : 행전체 or 열전체
# loc[]인덱스 : 행x열 조합
print(df.loc[cond, "이름"]) # df[조건] -> 행반환
print(df.loc[df["점수"].isna(), "이름"]) # df[조건] -> 행반환

    이름  점수     출석
1  이서연 NaN   True
4  정현우 NaN  False
    이름  점수     출석
1  이서연 NaN   True
4  정현우 NaN  False
1    이서연
4    정현우
Name: 이름, dtype: str
1    이서연
4    정현우
Name: 이름, dtype: str

In [11]:
df.isna().sum()

이름    0
점수    2
출석    1
dtype: int64

In [12]:
# 결측치 대체
print(df.isna().any()) # 데이터프레임 열에 누락값이 하나라도 있으면 True

print(df.isna().all()) # 데이터프레임 열이 모두 누락값이면 True

이름    False
점수     True
출석     True
dtype: bool
이름    False
점수    False
출석    False
dtype: bool

In [13]:
df

    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   NaN  False

In [14]:
df2 = df.dropna()
df2

    이름    점수    출석
0  김민준  85.0  True
3  최유진  75.0  True

In [15]:
df3 = df.dropna(subset=["출석"])
df3

    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
3  최유진  75.0   True
4  정현우   NaN  False

In [16]:
df4 = df.dropna(subset=df.columns) # 기본값
df4

    이름    점수    출석
0  김민준  85.0  True
3  최유진  75.0  True

In [17]:
df["점수"].fillna(100)

0     85.0
1    100.0
2     90.0
3     75.0
4    100.0
Name: 점수, dtype: float64

In [18]:
df2 = df
display(df)
df2["점수"] = df["점수"].fillna(100)
display(df2)
df

    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   NaN  False

    이름     점수     출석
0  김민준   85.0   True
1  이서연  100.0   True
2  박지훈   90.0   None
3  최유진   75.0   True
4  정현우  100.0  False

    이름     점수     출석
0  김민준   85.0   True
1  이서연  100.0   True
2  박지훈   90.0   None
3  최유진   75.0   True
4  정현우  100.0  False

In [19]:
df

    이름     점수     출석
0  김민준   85.0   True
1  이서연  100.0   True
2  박지훈   90.0   None
3  최유진   75.0   True
4  정현우  100.0  False

In [20]:
avg = df["점수"].mean()

In [21]:
df2 = df.copy()
df2["점수"] = df2["점수"].fillna(avg)
df2

    이름     점수     출석
0  김민준   85.0   True
1  이서연  100.0   True
2  박지훈   90.0   None
3  최유진   75.0   True
4  정현우  100.0  False

In [23]:
data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "성별": ["M", "F", None, "F", None] 
}

df = pd.DataFrame(data)

# mode()의 반환타입은 시리즈 타입이다. 결과값을 값을 가져오기 위해 위치값 [0]이 필요
mode_gender = df["성별"].mode()[0]

df["성별"] = df["성별"].fillna(mode_gender)

print(df)

    이름 성별
0  김민준  M
1  이서연  F
2  박지훈  F
3  최유진  F
4  정현우  F

In [24]:
data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "점수": [80, None, 90, 70, None]
}

df = pd.DataFrame(data)


print("평균:", df["점수"].mean())
print("합계:", df["점수"].sum())
print("최댓값:", df["점수"].max())
print("최솟값:", df["점수"].min())

print("개수:",df["점수"].count())

평균: 80.0
합계: 240.0
최댓값: 90.0
최솟값: 70.0
개수: 3