In [1]:
import pandas as pd

In [ ]:
# SQL 예
# 집합연산(UNION, ... 행, 열) -> concat 함수
# JOIN(key값(컬럼값) 합친다) -> merge 함수

In [2]:
df1 = pd.DataFrame({
    "이름": ["김민수", "이서연"],
    "점수": [80, 90]
})

df2 = pd.DataFrame({
    "이름": ["박지훈", "최유진"],
    "등급": ["A", "B"]
})

display(df1)
display(df2)

    이름  점수
0  김민수  80
1  이서연  90

    이름 등급
0  박지훈  A
1  최유진  B

In [3]:
df3 = pd.concat([df1, df2], axis=0, ignore_index=True)
df3

    이름    점수   등급
0  김민수  80.0  NaN
1  이서연  90.0  NaN
2  박지훈   NaN    A
3  최유진   NaN    B

In [4]:
df4 = pd.concat([df1, df2], axis=1, ignore_index=False)
df4

    이름  점수   이름 등급
0  김민수  80  박지훈  A
1  이서연  90  최유진  B

In [5]:
# join 매개변수 ? SQL JOIN과는 다르다
# outer / inner

In [7]:
pd.concat([df1, df2])

    이름    점수   등급
0  김민수  80.0  NaN
1  이서연  90.0  NaN
0  박지훈   NaN    A
1  최유진   NaN    B

In [8]:
pd.concat([df1, df2], join="inner")

    이름
0  김민수
1  이서연
0  박지훈
1  최유진

In [ ]:
# merge 함수 : SQL JOIN 유사 -> 어려워해야하는데 우리반?

In [9]:
import pandas as pd

df_customer = pd.DataFrame({
    "고객ID": [101, 102, 103, 104],
    "이름": ["홍길동", "김철수", "이영희", "박민수"]
})

df_score = pd.DataFrame({
    "고객ID": [101, 102, 103, 105],
    "점수": [90, 80, 95, 70]
})


display(df_customer)
display(df_score)

result = pd.merge(
    df_customer,
    df_score,
    on="고객ID",
    how="inner" # inner(기본값), left, right, outer
)

display(result)

   고객ID   이름
0   101  홍길동
1   102  김철수
2   103  이영희
3   104  박민수

   고객ID  점수
0   101  90
1   102  80
2   103  95
3   105  70

   고객ID   이름  점수
0   101  홍길동  90
1   102  김철수  80
2   103  이영희  95

In [10]:
result = pd.merge(
    df_customer,
    df_score,
    on="고객ID",
    how="left"
)

display(result)

   고객ID   이름    점수
0   101  홍길동  90.0
1   102  김철수  80.0
2   103  이영희  95.0
3   104  박민수   NaN

In [11]:
result = pd.merge(
    df_customer,
    df_score,
    on="고객ID",
    how="right"
)

display(result)

   고객ID   이름  점수
0   101  홍길동  90
1   102  김철수  80
2   103  이영희  95
3   105  NaN  70

In [12]:
result = pd.merge(
    df_customer,
    df_score,
    on="고객ID",
    how="outer"
)

display(result)

   고객ID   이름    점수
0   101  홍길동  90.0
1   102  김철수  80.0
2   103  이영희  95.0
3   104  박민수   NaN
4   105  NaN  70.0