In [ ]:
import pandas as pd # numpy, scikit-learn, ...

In [ ]:
# 시리즈 메서드
# pandas -> Series -> isna() 메서드
# pandas -> concat() 함수
# 메서드 호출 s = pd.Series() -> s.isna()
# 함수 호출 pd.concat()
# 시리즈 메서드, 데이터프레임 메서드 -> 수집, 탐색, 전처리, 분석, ...
# 모듈을 만든 이들이 어떤 기능은 함수로, 어떤 기능은 메서드
# 어떤 기능이 유사한 기능을 가진 함수도 존재, 메서드 존재 what? -> 코드의 결 or 개발자, 분석가, 과학자, ...성형... -> AI코드생성 -> 규칙X -> you 개입

In [2]:
df = pd.DataFrame({
    "이름":["김민수","이서연","박지훈"],
    "점수":[80, 90, 75] # None, NaN
})

df

    이름  점수
0  김민수  80
1  이서연  90
2  박지훈  75

In [3]:
a = df["점수"]
display(a)
display(type(a)) # 시리즈
display(a.dtype) # 숫자
display(a.info())

0    80
1    90
2    75
Name: 점수, dtype: int64

pandas.Series

dtype('int64')

<class 'pandas.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: 점수
Non-Null Count  Dtype
--------------  -----
3 non-null      int64
dtypes: int64(1)
memory usage: 156.0 bytes

None

In [5]:
df2 = df[["이름", "점수"]]
df

    이름  점수
0  김민수  80
1  이서연  90
2  박지훈  75

In [6]:
df2 = df[["점수"]] # df["점수"]
display(type(df2))
df2

pandas.DataFrame

   점수
0  80
1  90
2  75

In [7]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "직원ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "이름": ["김민준", "이서연", "박지훈", "최유진",
           "정현우", "강수빈", "조민서", "윤도현"],
    "부서": ["개발", "영업", "개발", "인사",
           "영업", "개발", "영업", "인사"],
    "성별": ["남", "여", "남", "여", "남", "여", "여", "남"],
    "매출": [850, 920, np.nan, 780, 1200, 650, 920, np.nan],
    "근무시간": [160, 172, 168, 155, 180, 150, 172, 158],
    "등급": ["B", "A", "B", "C", "A", "C", "A", None],
    "입사년도": [2020, 2019, 2021, 2022, 2018, 2023, 2019, 2022]
})

display(df)

   직원ID   이름  부서 성별      매출  근무시간   등급  입사년도
0   101  김민준  개발  남   850.0   160    B  2020
1   102  이서연  영업  여   920.0   172    A  2019
2   103  박지훈  개발  남     NaN   168    B  2021
3   104  최유진  인사  여   780.0   155    C  2022
4   105  정현우  영업  남  1200.0   180    A  2018
5   106  강수빈  개발  여   650.0   150    C  2023
6   107  조민서  영업  여   920.0   172    A  2019
7   108  윤도현  인사  남     NaN   158  NaN  2022

In [8]:
# 통계(수치 데이터), SQL 유사 : 집계함수들은 null값 빼고 처리
df["매출"]

0     850.0
1     920.0
2       NaN
3     780.0
4    1200.0
5     650.0
6     920.0
7       NaN
Name: 매출, dtype: float64

In [ ]:
df["매출"].count() # NaN 빼고 연산

np.int64(6)

In [10]:
len(df["매출"])

8

In [11]:
df["매출"].mean()

np.float64(886.6666666666666)

In [12]:
df["성별"].mode() # 빈도가 많은 값을 반환.

0    남
1    여
Name: 성별, dtype: str

In [13]:
df["부서"].mode()

0    개발
1    영업
Name: 부서, dtype: str

In [14]:
# sum, max, min, var, std
df["매출"].std()

np.float64(183.92027258208014)

In [22]:
df["매출"].var()

np.float64(33826.666666666664)

In [15]:
#quantile, median
df["매출"].median()

np.float64(885.0)

In [23]:
df["매출"].quantile(0.75)

np.float64(920.0)

In [24]:
df["매출"].describe()

count       6.000000
mean      886.666667
std       183.920273
min       650.000000
25%       797.500000
50%       885.000000
75%       920.000000
max      1200.000000
Name: 매출, dtype: float64

In [16]:
df["부서"].unique()

<StringArray>
['개발', '영업', '인사']
Length: 3, dtype: str

In [25]:
df["부서"].nunique()

3

In [18]:
df["부서"].value_counts()

부서
개발    3
영업    3
인사    2
Name: count, dtype: int64

In [19]:
df["부서"].mode() # 값반환 시리즈타입 반환

0    개발
1    영업
Name: 부서, dtype: str

In [ ]:
df["매출"]

0    개발
1    영업
2    개발
3    인사
4    영업
5    개발
6    영업
7    인사
Name: 부서, dtype: str

In [26]:
df["부서"].isna()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: 부서, dtype: bool

In [27]:
df["매출"].isnull()

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7     True
Name: 매출, dtype: bool

In [28]:
df["매출"].notna()

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
Name: 매출, dtype: bool

In [29]:
df["매출"].notnull()

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
Name: 매출, dtype: bool

In [ ]:
# NaN(결측치) 대체 : 대표값(평균, 중앙값, 최빈값, 시계열, ... 회귀값, ...)
# fillna

In [30]:
매출시리즈 = df["매출"]
매출시리즈

0     850.0
1     920.0
2       NaN
3     780.0
4    1200.0
5     650.0
6     920.0
7       NaN
Name: 매출, dtype: float64

In [31]:
매출시리즈 = df["매출"]
매출시리즈2 = 매출시리즈.fillna(round(매출시리즈.mean()))
매출시리즈2

0     850.0
1     920.0
2     887.0
3     780.0
4    1200.0
5     650.0
6     920.0
7     887.0
Name: 매출, dtype: float64

In [32]:
매출시리즈3 = 매출시리즈.dropna()
매출시리즈3

0     850.0
1     920.0
3     780.0
4    1200.0
5     650.0
6     920.0
Name: 매출, dtype: float64

In [33]:
# 정렬
df.columns

Index(['직원ID', '이름', '부서', '성별', '매출', '근무시간', '등급', '입사년도'], dtype='str')

In [34]:
df["입사년도"]

0    2020
1    2019
2    2021
3    2022
4    2018
5    2023
6    2019
7    2022
Name: 입사년도, dtype: int64

In [35]:
정렬입사년도 = df["입사년도"].sort_values(ascending=True)
정렬입사년도

4    2018
1    2019
6    2019
0    2020
2    2021
3    2022
7    2022
5    2023
Name: 입사년도, dtype: int64

In [36]:
정렬입사년도 = df["입사년도"].sort_values(ascending=False)
정렬입사년도

5    2023
3    2022
7    2022
2    2021
0    2020
1    2019
6    2019
4    2018
Name: 입사년도, dtype: int64

In [37]:
df["이름"]

0    김민준
1    이서연
2    박지훈
3    최유진
4    정현우
5    강수빈
6    조민서
7    윤도현
Name: 이름, dtype: str

In [ ]:
n1 = pd.Series([" ab ", " ab", "ab ", "a b"])
print(n1.str.strip()) # 앞뒤공백제거

0     ab
1     ab
2     ab
3    a b
dtype: str

In [39]:
n1 = pd.Series([" ab ", " ab", "ab ", "a b"])
print(n1.str.replace(" ","")) # 공백을 빈문자열로 변경

0    ab
1    ab
2    ab
3    ab
dtype: str

In [40]:
df

   직원ID   이름  부서 성별      매출  근무시간   등급  입사년도
0   101  김민준  개발  남   850.0   160    B  2020
1   102  이서연  영업  여   920.0   172    A  2019
2   103  박지훈  개발  남     NaN   168    B  2021
3   104  최유진  인사  여   780.0   155    C  2022
4   105  정현우  영업  남  1200.0   180    A  2018
5   106  강수빈  개발  여   650.0   150    C  2023
6   107  조민서  영업  여   920.0   172    A  2019
7   108  윤도현  인사  남     NaN   158  NaN  2022

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   직원ID    8 non-null      int64
 1   이름      8 non-null      str
 2   부서      8 non-null      str
 3   성별      8 non-null      str
 4   매출      6 non-null      float64
 5   근무시간    8 non-null      int64
 6   등급      7 non-null      str
 7   입사년도    8 non-null      int64
dtypes: float64(1), int64(3), str(4)
memory usage: 644.0 bytes

In [42]:
df["입사년도"].describe()

count       8.000000
mean     2020.500000
std         1.772811
min      2018.000000
25%      2019.000000
50%      2020.500000
75%      2022.000000
max      2023.000000
Name: 입사년도, dtype: float64

In [43]:
카테고리입사년도 = df["입사년도"].astype("category")
카테고리입사년도.describe()

count        8
unique       6
top       2019
freq         2
Name: 입사년도, dtype: int64

In [46]:
nums = pd.Series(["1", "2", "3", np.nan])
n2 = nums.astype(int) # 시리즈의 astype 메서드
# n3 = pd.to_numeric(nums) # 판다스모델의 to_numeric 함수
display(n2)
# display(n3)

ValueError: cannot convert float NaN to integer

In [47]:
nums = pd.Series(["1", "2", "3", np.nan])
# n2 = nums.astype(int) # 시리즈의 astype 메서드
n3 = pd.to_numeric(nums) # 판다스모델의 to_numeric 함수
# display(n2)
display(n3)

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [49]:
nums = pd.Series(["1", "2", "3", np.nan])
n2 = nums.astype(int)
display(n2)

ValueError: cannot convert float NaN to integer

In [48]:
nums = pd.Series(["1", "2", "3", np.nan, "abc"])
n3 = pd.to_numeric(nums, errors="coerce")
display(n3)

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
dtype: float64

In [50]:
df["매출"]

0     850.0
1     920.0
2       NaN
3     780.0
4    1200.0
5     650.0
6     920.0
7       NaN
Name: 매출, dtype: float64

In [51]:
df["매출"].where(df["매출"] > 900)

0       NaN
1     920.0
2       NaN
3       NaN
4    1200.0
5       NaN
6     920.0
7       NaN
Name: 매출, dtype: float64

In [52]:
df["매출"].mask(df["매출"] > 900, 500)

0    850.0
1    500.0
2      NaN
3    780.0
4    500.0
5    650.0
6    500.0
7      NaN
Name: 매출, dtype: float64

In [53]:
입사년도 = df["입사년도"]
입사년도

0    2020
1    2019
2    2021
3    2022
4    2018
5    2023
6    2019
7    2022
Name: 입사년도, dtype: int64

In [54]:
입사년도.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
Name: 입사년도, dtype: bool

In [55]:
입사년도2 = 입사년도.drop_duplicates()
입사년도2

0    2020
1    2019
2    2021
3    2022
4    2018
5    2023
Name: 입사년도, dtype: int64

In [57]:
# 시리즈 값 변경 메서드
# replace, map 메서드

영어부서 = df["부서"]
영어부서

0    개발
1    영업
2    개발
3    인사
4    영업
5    개발
6    영업
7    인사
Name: 부서, dtype: str

In [58]:
영어부서2 = 영어부서.replace({"개발":"Development"})
영어부서2

0    Development
1             영업
2    Development
3             인사
4             영업
5    Development
6             영업
7             인사
Name: 부서, dtype: str

In [60]:
영어부서3 = 영어부서.map({"개발":"Development", "영업":"M", "인사":"H"})
영어부서3

0    Development
1              M
2    Development
3              H
4              M
5    Development
6              M
7              H
Name: 부서, dtype: str

In [61]:
매출 = df["매출"]
매출

0     850.0
1     920.0
2       NaN
3     780.0
4    1200.0
5     650.0
6     920.0
7       NaN
Name: 매출, dtype: float64

In [64]:
# 구간별 값을 매핑하는 메서드 X
# apply(함수) 메서드 : apply 메서드 매개값으로 들어갈 함수 선언(람다를 사용 가능)

def 매출_등급(val):
    if pd.isna(val): # val 시리즈가 아니다. val.isna() X, pd.isna(값) 함수 사용
        return "결측치"
    elif val >= 1000:
        return "상"
    elif val >= 800:
        return "중"
    else:
        return "하"

등급 = 매출.apply(매출_등급)
등급

0      중
1      중
2    결측치
3      하
4      상
5      하
6      중
7    결측치
Name: 매출, dtype: str

In [65]:
# 누적 통계기술량
df["매출"].cummax()

0     850.0
1     920.0
2       NaN
3     920.0
4    1200.0
5    1200.0
6    1200.0
7       NaN
Name: 매출, dtype: float64

In [66]:
df["매출"].cumprod()

0    8.500000e+02
1    7.820000e+05
2             NaN
3    6.099600e+08
4    7.319520e+11
5    4.757688e+14
6    4.377073e+17
7             NaN
Name: 매출, dtype: float64

In [67]:
# 시계열 데이터 값 이동 shift 연산
df["매출"]

0     850.0
1     920.0
2       NaN
3     780.0
4    1200.0
5     650.0
6     920.0
7       NaN
Name: 매출, dtype: float64

In [68]:
df["매출"].shift()

0       NaN
1     850.0
2     920.0
3       NaN
4     780.0
5    1200.0
6     650.0
7     920.0
Name: 매출, dtype: float64

In [69]:
df["매출"].diff()

0      NaN
1     70.0
2      NaN
3      NaN
4    420.0
5   -550.0
6    270.0
7      NaN
Name: 매출, dtype: float64

In [70]:
df["매출"].pct_change()

0         NaN
1    0.082353
2         NaN
3         NaN
4    0.538462
5   -0.458333
6    0.415385
7         NaN
Name: 매출, dtype: float64

In [71]:
# isin, sample, to_frame, copy, equals
df["부서"].isin(["개발", "인사"])

0     True
1    False
2     True
3     True
4    False
5     True
6    False
7     True
Name: 부서, dtype: bool

In [72]:
df["이름"]

0    김민준
1    이서연
2    박지훈
3    최유진
4    정현우
5    강수빈
6    조민서
7    윤도현
Name: 이름, dtype: str

In [ ]:
# 모집단 -> 기술통계량 -> 불가능 -> 표본 -> 표본기술통계량 -> 모집단적용?

df["이름"].sample(2, random_state=7) # 7 -> 특정알고리즘 적용

4    정현우
2    박지훈
Name: 이름, dtype: str

In [74]:
names = df["이름"]
display(type(names))
display(names)

pandas.Series

0    김민준
1    이서연
2    박지훈
3    최유진
4    정현우
5    강수빈
6    조민서
7    윤도현
Name: 이름, dtype: str

In [75]:
df_names = names.to_frame()
display(type(df_names))
df_names

pandas.DataFrame

    이름
0  김민준
1  이서연
2  박지훈
3  최유진
4  정현우
5  강수빈
6  조민서
7  윤도현

In [78]:
s1 = pd.Series([1, 2])
s2 = pd.Series([1, 2])
s3 = s1.copy() # copy 메서드
s4 = s1 # 대입연산자

display(s1)
display(s2)
display(s3)
display(s4)

0    1
1    2
dtype: int64

0    1
1    2
dtype: int64

0    1
1    2
dtype: int64

0    1
1    2
dtype: int64

In [81]:
s1[0] = 7
s1
# s1 : 7, 2
# s2 : 0, 2
# s3 : 0, 2
# s4 : 0, 2

display(s2.equals(s1)) # T
display(s3.equals(s1)) # T
display(s4.equals(s1)) # T

False

False

True